apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tetragon/kustomization.yaml
  - falco/kustomization.yaml
  - monitoring/kustomization.yaml
dependsOn:
  - name: flux-system
    namespace: flux-system
